baseURL       = "https://boringlava.github.io"
languageCode  = "en-us"
title         = "Mae Saslaw"
theme         = "ronu-hugo-theme"

[[menu.main]]
	name = "Curriculum vitae"
	url  = "/cv/"

[[menu.main]]
  name = "Presentations"
  url  = "/presentations/"

  [params]
	authorNname = "Mae Saslaw"
	twitterURL  = "https://twitter.com/soilenjoyer"
	email       = "mae.saslaw@stonybrook.edu"
