baseURL       = "https://saslaw.github.io/"
title         = "Mae Saslaw"
theme         = "hugo-lithium"
relativeURLs = true
languageCode  = "en-us"
enableEmoji		= true

[[menu.main]]
	name = "Curriculum vitae"
	url  = "/cv/"
	weight = 1
[[menu.main]]
  name = "Recent work"
  url  = "/work/"
	weight = 2
[[menu.main]]
  name = "Notebooks"
  url  = "/notebooks/"
	weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"

[params]
	authorNname = "Mae Saslaw"
	email       = "mae.saslaw@stonybrook.edu"
	description	= "Recent work"

[social]
  github  = "https://github.com/saslaw"
  twitter = "https://twitter.com/soilenjoyer"
